ur5_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

ur5_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur5_joint_1
    - ur5_joint_2
    - ur5_joint_3
    - ur5_joint_4
    - ur5_joint_5
    - ur5_joint_6
    - ur5_joint_7

  constraints:
    goal_time: 2.0

  state_publish_rate: 100