ur5_joint_state_controller:

    type: joint_state_controller/JointStateController
    publish_rate: 50

ur5_joint_trajectory_controller:

    type: position_controllers/JointTrajectoryController
    state_publish_rate: 50

    joints:
        - ur5_joint1
        - ur5_joint2
        - ur5_joint3
        - ur5_joint4
        - ur5_joint5
        - ur5_joint6

    constraints:
        goal_time: 2.0

ur5_joint_group_pos_controller:

    type: position_controllers/JointGroupPositionController
    arm_id: ur5

    joints:
        - ur5_joint1
        - ur5_joint2
        - ur5_joint3
        - ur5_joint4
        - ur5_joint5
        - ur5_joint6

wsg_group_controller:

    type: effort_controllers/JointGroupPositionController
    arm_id: ur5
    
    joints:
        - wsg_base_mount_right_joint
        - wsg_base_mount_left_joint
    
    wsg_base_mount_right_joint:
        pid: {p: 100.0, i: 0.01, d: 10.0}

    wsg_base_mount_left_joint:
        pid: {p: 100.0, i: 0.01, d: 10.0}

